## MySQL image version
auth:
  rootPassword: my-password
  database: my_database
  username: my-user
  password: my-pass

volumePermissions:
  enabled: true

primary:
  persistence:
    enabled: false

secondary:
  replicaCount: 2
  persistence:
    enabled: false