apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: ilsoldier/eks-demo-app:1.1.1-14
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: java-app-config
              key: db-server
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: db_user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: java-app-secret
              key: db_pwd
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: java-app
# spec:
#   selector:
#     app: java-app
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080