apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.imageName }}:{{ .Values.imageTag }}"
        env:
        {{- range $key, $value := .Values.configData }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configName }}
              key: {{ $key }}
        {{- end }}

        {{- range $key, $value := .Values.secretData }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.secretName }}
              key: {{ $key }}
        {{- end }}

        {{- range $key, $value := .Values.envData }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
