apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: {{ .Values.serviceData.servicePort }}
    targetPort: {{ .Values.serviceData.containerPort }}
